### ISSUE TITLE
Bad call to socket.send

### ISSUE THREAD

**Issue by Downchuck** [danoctavian/bluntly#1]
warn: direct TCP connection attempt failed with error Error: timeout
info: Trying a hole punching connection over UDP on the same port.

TypeError: First argument must be a buffer object.
    at Socket.send (dgram.js:245:11)
    at send (/Users/.../Desktop/bluntly/node-bluntly/hole-punch.js:56:10)

**Comment by danoctavian** [comment]
thanks dude, on it
